controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app_register:
    path: /register
    controller: App\Controller\RegistrationController::register
    methods: POST
app_verify_email:
    path: /verify/email
    controller: App\Controller\RegistrationController::verifyUserEmail
    methods: GET
app_login:
    path: /login
    controller: App\Controller\SecurityController::login
    methods: POST
app_user_show:
    path: /user
    controller: App\Controller\UserController::show
    methods: GET